QuanLiKhoHang_DoAnWeb/Models/SaleOrders.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace QuanLiKhoHang_DoAnWeb.Models
{
    public class SaleOrders
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Khách hàng")]
        public int ClientId { get; set; }

        [Display(Name = "Khách hàng")]
        [ForeignKey("ClientId")]
        public Clients client { get; set; }

        [Display(Name = "Chú thích")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Ngày đặt hàng")]
        public DateTime OrderDate { get; set; }

        [Display(Name = "Xác nhận")]
        public bool isConfirmed { get; set; }

        [Display(Name = "Tổng cộng")]
        public float Total { get; set; }
    }
}

QuanLiKhoHang_DoAnWeb/Models/ViewModels/SaleOrdersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuanLiKhoHang_DoAnWeb.Models.ViewModels
{
    public class SaleOrdersViewModel
    {
        public SaleOrders saleOrder { get; set; }
        public IEnumerable<Clients> client { get; set; }
        public IEnumerable<SaleOrderDetails> saleOrderDetails { get; set; }
        public IEnumerable<Products> product { get; set; }

    }
}

QuanLiKhoHang_DoAnWeb/Areas/Manager/Controllers/SaleOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuanLiKhoHang_DoAnWeb.Data;
using QuanLiKhoHang_DoAnWeb.Models;
using QuanLiKhoHang_DoAnWeb.Models.ViewModels;

namespace QuanLiKhoHang_DoAnWeb.Areas.Manager.Controllers
{
    [Area("Manager")]
    public class SaleOrdersController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public SaleOrdersViewModel SaleOrderVM { get; set; }

        public SaleOrdersController(ApplicationDbContext db)
        {
            _db = db;
            SaleOrderVM = new SaleOrdersViewModel()
            {
                client = _db.clients.ToList(),
                saleOrder = new Models.SaleOrders()
            };
        }

        public async Task<IActionResult> Index()
        {
            var saleorder = _db.saleOrders.Include(m => m.client);
            return View(await saleorder.ToListAsync());
        }

        public IActionResult Create()
        {
            return View(SaleOrderVM);
        }

        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST()
        {
            if (!ModelState.IsValid)
            {
                return View(SaleOrderVM);
            }

            _db.saleOrders.Add(SaleOrderVM.saleOrder);

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            SaleOrderVM.product = _db.products.ToList();
            SaleOrderVM.saleOrder = await _db.saleOrders.Include(m => m.client).SingleOrDefaultAsync(m => m.Id == id);

            SaleOrderVM.saleOrderDetails = from p in _db.saleOrders
                                           join q in _db.saleOrderDetails on p.Id equals q.SaleOrderId
                                           where p.Id == SaleOrderVM.saleOrder.Id
                                           select new SaleOrderDetails()
                                           {
                                               SaleOrderId = p.Id,
                                               ExportProductId = q.ExportProductId,
                                               Description = q.Description,
                                               Quantity = q.Quantity,
                                               Total = q.Total
                                           };
                                                                    
            if (SaleOrderVM.saleOrder == null)
            {
                return NotFound();
            }

            return View(SaleOrderVM);
        }

        [HttpGet]
        public ActionResult CreateDetails(string id)
        {
            return RedirectToAction("Create", "SaleOrderDetails", new { id = id});
        }

        public async Task<IActionResult> Delete(int? Id)
        {
            if (Id == null)
                return NotFound();

            var saleOrder = await _db.saleOrders.FindAsync(Id);
            if (saleOrder == null)
                return NotFound();

            return View(saleOrder);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var saleOrder = await _db.saleOrders.FindAsync(id);
            int saleOrderDetailCount = _db.saleOrderDetails.Count(m => m.SaleOrderId == id);

            if (saleOrderDetailCount != 0)
            {
                SetAlert("Lỗi, không thể xóa mục này. Vui lòng kiểm chắc chắn lệnh này trống và thử lại", "error");
            }
            else
            {
                _db.saleOrders.Remove(saleOrder);
                await _db.SaveChangesAsync();
                SetAlert("Xóa thành công", "success");
            }
            return RedirectToAction(nameof(Index));
        }

        protected void SetAlert(string message, string type)
        {
            TempData["AlertMessage"] = message;
            if (type == "error")
            {
                TempData["AlertType"] = "alert-danger";
            }

            if (type == "success")
            {
                TempData["AlertType"] = "alert-success";
            }
        }

        public IActionResult OrderConfirmation(int? id)
        {
            if (id == null)
            {
                SetAlert("Đã xảy ra lỗi khi xác nhận đơn hàng", "error");
                return RedirectToAction(nameof(Index));
            }
            else
            {
                var SaleOrder = _db.saleOrders.Where(m => m.Id == id).FirstOrDefault();
                SaleOrder.isConfirmed = true;
                _db.SaveChanges();
                SetAlert("Xác nhận thành công đơn hàng id = " + id, "success");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

QuanLiKhoHang_DoAnWeb/Areas/Manager/Views/SaleOrders/Create.cshtml
@model QuanLiKhoHang_DoAnWeb.Models.ViewModels.SaleOrdersViewModel
@using QuanLiKhoHang_DoAnWeb.Extensions

@{
    ViewData["Title"] = "Create";
}

<br />
<h2 class="text-info">Tạo lệnh bán(xuất kho)</h2>

<form method="post" enctype="multipart/form-data">
    <div class="p-4 border rounded">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-2">
                <label asp-for="saleOrder.ClientId"></label>
            </div>
            <div class="col-3">
                <select asp-for="@Model.saleOrder.ClientId" asp-items="Model.client.ToSelectListItem(Model.saleOrder.ClientId)" class="form-control"></select>
            </div>
        </div>
    <br />
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="saleOrder.Description"></label>
            </div>
            <div class="col-6">
                <input asp-for="saleOrder.Description" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="saleOrder.OrderDate"></label>
            </div>
            <div class="col-5">
                <input asp-for="saleOrder.OrderDate" type="datetime-local" class="form-control" />
            </div>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Create" />
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>
</form>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QuanLiKhoHang_DoAnWeb/Areas/Manager/Views/SaleOrders/Delete.cshtml
@model QuanLiKhoHang_DoAnWeb.Models.SaleOrders
@{
    ViewData["Title"] = "Delete";
}

<h1>Xoá ngành hàng</h1>
<br />
<h2 class="text-info">Bạn có thật sự muốn nhà cung cấp này?</h2>

<form method="post" asp-action="Delete">
    <div class="p-4 border rounded">
        <input type="hidden" asp-for="Id" />
        <div class="form-group row">
            <div class="col-3 ">
                <label asp-for="Id"></label>
            </div>
            <div class="col-5">
                <input asp-for="Id" disabled />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3 ">
                <label asp-for="Description"></label>
            </div>
            <div class="col-5">
                <input asp-for="Description" disabled />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3 ">
                <label asp-for="OrderDate"></label>
            </div>
            <div class="col-5">
                <input asp-for="OrderDate" disabled />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3 ">
                <label asp-for="Total"></label>
            </div>
            <div class="col-5">
                <input asp-for="Total" disabled />
            </div>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" asp-route-id="@Model.Id" value="Xoá" />
            <a asp-action="Index" class="btn btn-success">Quay lại</a>
        </div>
    </div>
</form>

@section Scripts
{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QuanLiKhoHang_DoAnWeb/Areas/Manager/Views/SaleOrders/Details.cshtml
@model QuanLiKhoHang_DoAnWeb.Models.ViewModels.SaleOrdersViewModel
@using QuanLiKhoHang_DoAnWeb.Extensions
@using System.Globalization
<br />
<h2 class="text-info">Chi tiết đơn hàng</h2>

@{int id = Model.saleOrder.Id; }
<div class="p-4 border rounded row">
    <div class="col-8">
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="saleOrder.client"></label>
            </div>
            <div class="col-8">
                <input asp-for="saleOrder.client.Name" readonly class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="saleOrder.Description"></label>
            </div>
            <div class="col-8">
                <input asp-for="saleOrder.Description" readonly class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="saleOrder.OrderDate"></label>
            </div>
            <div class="col-5">
                <input asp-for="saleOrder.OrderDate" type="datetime-local" class="form-control" />
            </div>
        </div>
        <br />
        <div class="col-14 text-right">
            <a asp-action="CreateDetails" asp-controller="SaleOrders" asp-route-id="@id" class="btn btn-info"><i class="fas fa-plus"></i>&nbsp; Thêm danh mục </a>
        </div>
        <br />
        <div>
            <table class="table table-striped border">
                <tr class="table-info">
                    <th>
                        @Html.DisplayName("Tên sản phẩm")
                    </th>
                    <th>
                        @Html.DisplayName("Ghi chú")
                    </th>
                    <th>
                        @Html.DisplayName("Số lượng")
                    </th>
                    <th>
                        @Html.DisplayName("Đơn giá")
                    </th>
                </tr>
                @foreach (var item in Model.saleOrderDetails)
                {
                    var productName = Model.product.First(i => i.Id == item.ExportProductId);

                    <tr>
                        <td>
                            @Html.DisplayFor(m => productName.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.Quantity)
                        </td>
                        <td>
                            @{ 
                            CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN");
                            }
                            @String.Format(cul.NumberFormat, "{0:c}", item.Total)
                        </td>
                    </tr>
                }
            </table>
        </div>

        <br />
        <div class="form-group">
            <a asp-action="Index" class="btn btn-success">Quay lại</a>
            @if (Model.saleOrder.isConfirmed == false)
            {
                <a asp-action="OrderConfirmation" asp-route-id="@Model.saleOrder.Id" class="btn btn-warning">Xác nhận đơn hàng</a>
            }
        </div>
    </div>
</div>

QuanLiKhoHang_DoAnWeb/Areas/Manager/Views/SaleOrders/Index.cshtml
@model IEnumerable<QuanLiKhoHang_DoAnWeb.Models.SaleOrders>
@using System.Globalization
@{
    ViewData["Title"] = "Index";
}

<br />
<br />

<div class="row">
    <div class="col-6">
        <h2 class="text-info">Danh sách lệnh xuất kho</h2>
    </div>
    <div class="col-6 text-right">
        <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i>&nbsp; Tạo lệnh xuất kho mới </a>
    </div>
</div>

<br />
<div>
    <table class="table table-striped border">
        <tr class="table-info">
            <th>
                @Html.DisplayNameFor(m => m.client.Name)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Description)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Total)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.isConfirmed)
            </th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(m => item.client.Name)
        </td>
        <td>
            @Html.DisplayFor(m => item.Description)
        </td>
        <td>
            @Html.DisplayFor(m => item.OrderDate)
        </td>
        <td>
            @{
                CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN");
            }
            @String.Format(cul.NumberFormat, "{0:c}", item.Total)
        </td>
        <td>
            @Html.DisplayFor(m => item.isConfirmed)
        </td>
        <td>
            <partial name="_TableButtonPartial" model="item.Id" />
        </td>
    </tr>
        }
    </table>
</div>